services:
  postgres_db:
    build: ./datasets/postgres
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '${POSTGRES_PORT}:5432'
    volumes:
      - ./datasets/postgres/adventure:/adventure
      - ./datasets/postgres/sales:/sales
      - ./datasets/postgres/init-postgres-adventuredb.sql:/docker-entrypoint-initdb.d/init-postgres-adventuredb.sql
      - ./datasets/postgres/init-postgres-salesdb.sql:/docker-entrypoint-initdb.d/init-postgres-salesdb.sql
    networks:
      - postgres-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-admin@admin.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-admin}
    ports:
      - "${PGADMIN_PORT:-5433}:80"
    networks:
      - postgres-network
    depends_on:
      - postges_db
    volumes:
      - pgadmin-data:/var/lib/pgadmin

networks:
  postgres-network:
    driver: bridge

volumes:
  postgres-data:
  pgadmin-data: